### ISSUE TITLE
Wrong direction given when VLSC is not working.

### ISSUE THREAD

**Issue by msmith91185** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#3] opened 2018-02-26 17:11 UTC
"Direct customers can submit a request from their Office 365 admin center or contact support."

Office 365 support currently does not have a download link this product nor know what to do when it is missing. Multiple contact resulted in the same. If there is an option this should be communicated to that team so that they can provide the support promised on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8ca0ba7-ad2d-e079-813a-b4e2d622de96
* Version Independent ID: 9c5e5594-ebff-f90f-fe73-71b545c3b2e7
* [Content](https://docs.microsoft.com/en-us/officeonlineserver/office-online-server#feedback)
* [Content Source](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/office-online-server.md)
* Service: unspecified

**Comment by lorenahuangliu** [comment] 2018-03-12 21:57
Hi there, thank you very much for your feedback. I've been actively working with our support center contacts to ensure that agents are aware of the download link that they can provide. You should be able to successfully obtain the link from support agents now.

Best,
Lorena | Office Online Server PM

**Comment by lorenahuangliu** [comment] 2018-04-05 20:38
Hi there, I'm closing the issue as per my reply above. Please feel free to reach out if you have further questions. 

Thanks,
Lorena | Office Online Server PM

**Comment by isaacgandalf** [comment] 2018-04-12 17:17
Hi Lorena,

May I know what this download link is?
Thanks!

**Comment by lorenahuangliu** [comment] 2018-04-12 17:30
Hi @isaacgandalf, 

I apologize, I am not able to provide the link to customers. Instead, you might follow the instructions on here (https://docs.microsoft.com/en-us/OfficeOnlineServer/office-online-server) to determine how to obtain OOS depending on your license. 

Thanks,
Lorena | Office Online Server PM

**Comment by isaacgandalf** [comment] 2018-04-12 20:51
Thanks for the prompt reply Lorena. I'm actually a support engineer for Office 365 Business myself and have encountered such a question from one of our customers, and I couldn't find anyone who knew of this download link. The ticket was created via the Need Help widget.

**Comment by lorenahuangliu** [comment] 2018-04-18 15:05
Hi @isaacgandalf ,

Are you able to contact me through email so that I can provide the information necessary? 

Thanks,
Lorena

**Comment by lorenahuangliu** [comment] 2018-04-18 16:07
Closing issue as it was resolved through communication with Isaac..

**Comment by cbaerike** [comment] 2018-08-01 02:25
Hi @lorenahuangliu and @isaacgandalf,

Would you be able share the solution? If not publicly, then at least with the rest of the Office 365 support team? I followed the advice given above and opened a ticket through my Office 365 Admin Center, and out of 3 replies so far, I've been sent in 3 different directions:
here: https://www.microsoft.com/licensing/servicecenter,
here: https://support.microsoft.com/en-us/assistedsupportproducts#gsproductselector,
and here: askpts@microsoft.com 

Can someone please either update the internal documentation about handling such requests, or the documentation above with the proper procedures?

Thanks,
Christian

**Comment by isaacgandalf** [comment] 2018-08-01 06:02
Hi Christian,
I apologize for this inconvenience. Can you give me the open case number and I'll have a look at it, and possibly contact the tech working on it.

Thanks,
Isaac

**Comment by cbaerike** [comment] 2018-08-01 15:11
Thanks for looking into this! The case number is 10907500.

Thanks,
Christian

**Comment by isaacgandalf** [comment] 2018-08-02 01:19
@cbaerike 
Hi Christian,

I have updated the case notes with the relevant information. It will now be up to the case owner to decide how to proceed, depending on policies that may be in place.

However, please review the licensing requirements for Office Online Server to verify eligibility:
https://www.microsoft.com/en-us/microsoft-365/blog/2017/04/18/office-online-server-april-2017-release/

https://www.microsoft.com/en-us/Licensing/product-licensing/products.aspx (download the English version for Product Terms)

**Comment by musashiharuno** [comment] 2018-08-06 03:13
Exchange Server 2013  for Office Web Apps Server did support , I think it post it wrongly.

quoted from 

https://blogs.technet.microsoft.com/admoore/2015/12/18/wac-oos-oos-and-wac/
Before we move on, take in the following:

Exchange 2013 uses Office Web Apps Server and does not support Office Online Server.

Exchange 2016 uses Offline Online Server and does not support Office Web Apps Server.

Exchange 2013 was an Organization level configuration.

----------------------
post do remedy the article

**Comment by cbaerike** [comment] 2018-08-07 04:29
@musashiharuno - You may want to post this in a separate feedback thread, as it will likely get overlooked in this one.

On topic: It seems like Office 365 customers are still SOL. Even after @isaacgandalf updated my case as mentioned above, I'm getting the same response (word for word!). Office 365 support is either unwilling or unable to help.

@lorenahuangliu - Can you please update the article and either remove the recommendation to open a ticket through the Office 365 admin center, or provide further details with the magical keywords?

Thanks,
Christian

**Comment by musashiharuno** [comment] 2018-08-07 16:04
@cbaerike haha, got your point,
OOS for Vol. License is for OnPrem with SharePoint & Exchange integration. 
OOS for Office365, in other words, built-in SharePoint Online & Exchange Online OWA.

frankly speaking, the product introduction/description sometimes is quite vague that not enough to express its real meaning. 

personally, I am afraid it can be a separate service for client level since OOS is the server level product. It can't be shipped with Office365 as the standalone licensing.

otherwise, they will clarify the statements in a "plain text".

for the wrong info I raised, I think I might go through the internal process despite of the long process as well. 

Thanks

**Comment by craigit000** [comment] 2018-08-30 16:54
I am having this same exact problem

**Comment by AndreaBarr** [comment] 2018-09-18 21:47
@msmith91185 Thank you for this feedback. 

It looks like your issue has been resolved. If this is not the case please re-open this issue. If there is another issue please open a new issue or contact support.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by lorenahuangliu** [comment] 2019-01-10 21:40
@tseward could you message me the support contact that you have been in communication with? It seems that the issue is how each team interprets our internal guidance article on the topic. We've made amendments to increase clarity but it would be helpful to get direct feedback from agents.

**Comment by cmruppe** [comment] 2019-01-11 19:57
I'm also suffering from the O365 support team not understanding licensing per this page.  I'm not sure I know if I'm applying licensing correctly either.  I've opened a support ticket and they seem to think the only way to get the setup.exe is to go through Volume Licensing.  We really need this for Excel Web Part functionality of our on-premise SharePoint environment, and we do have O365 licensing that seems to fit the license requirements for OOS download.

**Comment by lorenahuangliu** [comment] 2019-01-11 21:58
@cmruppe thank you for letting me know. @tseward has provided me with a thread that he's been part of and I've been working with them to figure out how to best get the message across. Could you private message me your point of contact as well?

**Comment by eschrader** [comment] 2019-03-22 22:33
Download it from MSDN https://my.visualstudio.com/downloads?wt.mc_id=o~msft~devcom~resources if you have an account. Much easier than a VLK. Using for DEV

**Closed** 2019-06-05 20:50 UTC

**Comment by paololec** [comment] 2019-11-11 16:31
I open a request with office 365 support and it unable to give me the link!!!! Please update how with office365 I can retrieve the iso!!!
